## YAML Template.
---
CC\TestBundle\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    login:
      type: string
      length: 30
    password:
      type: string
      length: 50
    email:
      type: string
      length: 30
    secondname:
      type: string
      length: 30
    firstname:
      type: string
      length: 30
    patronymic:
      type: string
      length: 30